# Generated by Django 5.2.5 on 2025-09-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEpi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='email',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(default='Desconhecida', max_length=100),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='setor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('Em uso', 'Em uso'), ('Devolvido', 'Devolvido')], default='Em uso', max_length=10),
        ),
        migrations.AddField(
            model_name='epi',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='epi',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epi',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
