# Generated by Django 5.2.5 on 2025-09-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEpi', '0002_remove_colaborador_email_colaborador_funcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
