# Generated by Django 5.2.5 on 2025-09-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEpi', '0003_emprestimo_data_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_real_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
